"""Initial database

Revision ID: c2850628d8b2
Revises: 
Create Date: 2024-06-08 20:36:02.712419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2850628d8b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_commits',
    sa.Column('commit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('commit_id')
    )
    op.create_table('commit_metrics',
    sa.Column('commit_id', sa.Integer(), nullable=False),
    sa.Column('execution_time', sa.Time(), nullable=False),
    sa.Column('allocated_memory', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commit_id'], ['user_commits.commit_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('commit_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commit_metrics')
    op.drop_table('user_commits')
    op.drop_table('users')
    # ### end Alembic commands ###
